#!/bin/bash
w=$(cat /etc/hosts | grep 'dt' | cut -d' ' -f3 | sort -nr)
# w = hostname

for i in $w
do
   hls &>/dev/null
   if [ "$?" == "1" ]; then 
     ssh $i sudo poweroff
     if [ "$?" == "0" ]; then
       echo -e "$i poweroff \n"
     fi
   else
     stopyarn && stophdfs
     [ "$?" == "0" ]&&ssh $i sudo poweroff
   fi
done 
