#!/bin/bash

u=$(whoami)

[ "$#" != 1 ] && echo "puthdfs filename" && exit 1

hls && [ "$?" == "1" ] && starthdfs &>/dev/null
[ "$?" == "0" ] &&echo "hdfs start"

hdfs dfs -ls /user/${u}/dataset &>/dev/null
if[ "$?" == "0" ]
then hdfs dfs -put -r ${1} /user/${u}/dataset
else hdfs dfs -mkdir -p /user/${u}/dataset && hdfs dfs -put -r ${1} /user/${u}/dataset
fi
if [ "$?" == "0" ]
then echo "${1}file put ok"
else put file false
fi 
